#sylius_shop_partial_cart_add_item_ajax:
gally_filter_view_more_ajax:
    path: /viewMore/{filterField}
    methods: [ GET ]
    defaults:
        _controller: Gally\SyliusPlugin\Controller\Filter::viewMore
        _format: json
