sylius_twig_hooks:
    hooks:
        'sylius_shop.base.header.content':
            search_bar:
                template: '@GallySyliusPlugin/shop/shared/components/header/search/search_bar.html.twig'
                priority: 250
                
        'sylius_shop.base.header':
            search_bar:
                template: '@GallySyliusPlugin/shop/shared/components/header/search/search_bar_mobile.html.twig'
                priority: 150

        'sylius_shop.product.search.content':
            breadcrumbs:
                template: '@GallySyliusPlugin/shop/product/search/content/breadcrumbs.html.twig'
                component: ~
                props: ~
                priority: 120

        'sylius_shop.product.search.content.body.main':
            header:
                template: '@GallySyliusPlugin/shop/product/search/content/body/main/header.html.twig'
                component: ~
                props: ~
                priority: 350
                
        'sylius_shop.product.index.content.body.main.filters':
            filter_button:
                template: '@GallySyliusPlugin/shop/product/search/content/body/main/filters/filter_button.html.twig'
                priority: 100

        'sylius_shop.product.search.content.body.main.filters':
            search:
                template: '@GallySyliusPlugin/shop/product/search/content/body/main/filters/search.html.twig'
            filter_button:
                template: '@GallySyliusPlugin/shop/product/search/content/body/main/filters/filter_button.html.twig'
                priority: 100

        'sylius_shop.product.search.content.body.sidebar':
            taxonomy:
                enabled: false
            gally_filters:
                template: '@GallySyliusPlugin/shop/product/search/content/body/sidebar/filters.html.twig'

        'sylius_shop.base#stylesheets':
            gally:
                template: "@GallySyliusPlugin/shop/events_stylesheets.html.twig"
                priority: 0
        
        'sylius_shop.base#javascripts':
            gally:
                template: "@GallySyliusPlugin/shop/events_javascript.html.twig"
                priority: 0

        'sylius_shop.product.index.content.body.sidebar':
            gally_filters:
                template: '@GallySyliusPlugin/shop/product/index/content/body/sidebar/filters.html.twig'
                priority: 0

        'sylius_shop.product.index.content.body.main.filters.search':
            filter:
                template: '@GallySyliusPlugin/shop/product/index/content/body/main/filters/search/filter.html.twig'

        
        'sylius_shop.product.index.content.body.main.filters.controls':
            sort:
                template: '@GallySyliusPlugin/shop/product/index/content/body/main/filters/controls/sorting.html.twig'
                

        'sylius_shop.product.index.content.body.main.filters.controls.sorting':
            menu:
                component: 'gally_shop:product:sorting'
                props:
                    template: '@GallySyliusPlugin/shop/product/index/content/body/main/filters/controls/sorting/menu.html.twig'
                template: ~
            toggle:
                enabled: false
